version: '3.8'

services:
  db:
    container_name: "tutorial_db"
    build: 
      context: .
      dockerfile: db.Dockerfile
    network: 
      - default 
    ports:
     
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "jasper"
      MYSQL_PASSWORD: "admin123"  
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password